### ISSUE TITLE
Add syntax highlighting in code samples

### ISSUE THREAD

**Issue by sanette** [sanette/ocaml-tutorial#3]
See
https://github.com/ocaml/ocaml/issues/8718

**Comment by sanette** [comment]
use Higlo?
http://zoggy.github.io/higlo/refdoc/Higlo.html

**Comment by sanette** [comment]
OK! higlo is cool.
This is mostly done!
 A few codes still escape the process, either because they have html in the code (underlines) or only "pre" tags  without .caml-input class.

**Comment by XVilka** [comment]
Note though, that Higlo seems abandoned and wont support newer OCaml syntax: https://github.com/zoggy/higlo/issues/3
The latest commit was almost 3 years ago https://github.com/zoggy/higlo/commits/master

**Comment by sanette** [comment]
true, sadly. I'm going to ask the author for confirmation.

**Comment by sanette** [comment]
closing this because now (>=4.10) code highlighting should be done directly via LaTeX
